### ISSUE TITLE
Warning: Failed propType: Invariant Violation: Invalid props.style key `fontSize` supplied to `RCTView`. Bad object: {   "width": 414,   "fontSize": 13 }

### ISSUE THREAD

**Issue by hagsteel** [peter4k/React-Native-FMPicker#1]
It seems like the `fontSize` style is not valid here:
https://github.com/peter4k/React-Native-FMPicker/blob/master/index.js#L105

**Comment by peter4k** [comment]
Thank you, just fixed this issue

**Comment by jackuhan** [comment]
use xxxStyle: Text.propTypes.style

**Comment by CarbonChili** [comment]
use xxxStyle: Text.propTypes.style

What is this ...?
