### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by montogeek** [peter4k/React-Native-FMPicker#6]
Hi!

Thanks for this component!

I am getting this warning for every `PickerItemIOS` component that is created.
`Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `Component`.`

I am using ReactNative 0.18.

**Comment by montogeek** [comment]
Probably related to this: https://github.com/rackt/react-router/issues/1799#issuecomment-171519662

**Comment by montogeek** [comment]
Uhmm, this is already fixed but not published to npm. Could you please update it?

Thanks!

**Comment by peter4k** [comment]
@montogeek was trying to add new feature..turns out I don't have time to do that. Will publish now. Thanks!

**Comment by montogeek** [comment]
@peter4k Sad to hear that :( This is a good component! Hopefully you will find the time. Thanks for your time
